language: cpp
matrix:
  include:
    - name: "ARCH=arm64 LD=ld.lld REPO=linux-next"
      env: ARCH=arm64 LD=ld.lld-10 REPO=linux-next
compiler: gcc
os: linux
sudo: required
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - |
    travis_wait 180 \
    docker run \
        --env ARCH=${ARCH} \
        --env LD=${LD} \
        --env REPO=${REPO} \
        --rm \
        --workdir /travis \
        --volume ${TRAVIS_BUILD_DIR}:/travis \
        clangbuiltlinux/debian:llvm${LLVM_VERSION:-10}-latest /bin/bash -c './env-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
notifications:
  email:
    recipients:
      - natechancellor@gmail.com
    on_success: never
    on_failure: always
